version: '3'
services:
  #
  # MongoDB Database
  #
  # Version 3.4 running default
  # settings. Used for Backend API data
  # storage.
  #
  # Accessible from Host:
  #
  # Server: localhost
  # Ports: 27017, 27018, 27019
  # Username: postgres
  # Password:
  #
  # ENV database__name using for upload intial database dump
  #
  database:
    container_name: backend-database
    image: mongo:3.4
    expose:
      - 27017-27019
    ports:
      - 57017-57019:27017-27019
    volumes:
      - ./docker/database:/usr/src/container
    environment:
      - database__name=backend
    command: sh /usr/src/container/init.sh

  #
  # Backend API Application
  #
  # Node.js Instance running Hapi.
  # Requires MongoDB be running before starting.
  #
  application:
    container_name: backend-application
    image: node:8
    expose:
      - 3000
      - 9229
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./docker/application:/usr/src/container
      - ./:/usr/src/app
    depends_on:
      - database
      - mailer
    environment:
      - NODE_ENV=debug
      - server__port=3000
      - database__uri=mongodb://backend-database:27017/backend
    command: sh /usr/src/container/init.sh

  #
  # SMTP server for sending emails
  #
  # That server have and web interface for displaying catched emails that available on 1080 port
  #
  mailer:
    container_name: backend-mailer
    image: schickling/mailcatcher
    expose:
      - 1025
      - 1080
    ports:
      - 1025:1025
      - 1080:1080
    environment:
      - MAILCATCHER_PORT_1025_TCP_ADDR=1025

  #
  # NGINX Reverse proxy
  #
  # Reverse proxy for allow to receive access to entrypoints over DNS names
  #
  reverseproxy:
    container_name: reverse-proxy
    image: nginx
    volumes:
      - ./docker/reverseproxy/default.conf:/etc/nginx/conf.d/mysite.template
    expose:
      - 8080
    ports:
      - 80:8080
    depends_on:
      - application
      - mailer
    environment:
      - APPLICATION_UPSTREAM=backend-application:3000
      - APPLICATION_HOSTNAME=backend.app.local
      - MAILER_UPSTREAM=backend-mailer:1080
      - MAILER_HOSTNAME=mailer.app.local
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
